# Generated by Django 2.0 on 2018-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postname',
            new_name='post_name',
        ),
        migrations.AlterField(
            model_name='userpost',
            name='mob_num',
            field=models.IntegerField(),
        ),
    ]
